service: rcs-graphql

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  region: us-east-1
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline
functions:
  graphql:
    handler: dist/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
